### ISSUE TITLE
review comments based on JOSS submissin

### ISSUE THREAD

**Issue by PeerHerholz** [BrkRaw/brkraw#13]
Hello everyone,

my name is Peer and I'm one of the reviewers of the manuscript you've submitted to [JOSS](https://github.com/openjournals/joss-reviews/issues/2277) regarding this repository and tool.

Based on my first round of review, I would like to provide some feedback regarding the review points I did not checked and I think need just a little more work to bring this already great manuscript home. The respective points will be outlined below. If you have the impression that my feedback is not constructive, my wording to harsh, I misunderstood something and/or have any other questions, please let me know.

### Documentation

- [x] the `statement of need` could be more precisely outlined and described on the landing page following JOSS guidelines: "...what problems the software is designed to solve and who the target audience is?"
- [x] while there's already information regarding different use cases and functionality, the respective parts could/should be demonstrated on data: a step-step walkthrough would be great, converting real world example data 
- [x] regarding the `API`: I checked your respective [jupyter notebook](https://github.com/brkraw/bruker/blob/master/examples/BrkRaw_PythonAPI.ipynb) and would like to suggest to add more information and description to this notebook, explaining things a bit more in depth. Furthermore, you could think about adding this notebook in an interactive version (through the amazing [binder project](https://mybinder.org/)) via a badge to your documentation.

### Software
- [x] While I know that your software is not "classic" when it comes to `automated tests`, I think adding some would be great in order to ensure functionality in the future. Maybe certain parts of the `API` could be tested, that is if data is converted as expected?

### Repository and Community
- [x] It would be great if you could include resources that make it easier for the community to interact with you as developers. This could/should entail an `Issue template`, `Contributing guidelines` and information regarding where to get `support`.

### General
- [x] The writing of the paper could be improved (a few missing words/articles here and there, present/past, etc.).
- [x] The `Naveau:2019` reference is not correctly rendered. Could you please check if that's maybe a typo in your submission or a problem on `JOSS`' end?

Again, if you have any questions regarding my comments, please don't hesitate to let me know. If you consider addressing them, I think it would be great to submit one PR for each comment to ensure traceability during the review process and beyond. I would like to thank you again for submitting this interesting manuscript.

I hope you and your loved ones are doing ok in these difficult times.

Best regards, Peer

**Comment by dvm-shlee** [comment]
@PeerHerholz Thank you for the useful and detailed comments. We will update the package according to each item and will generate PR for each item as well. Regarding building community, as up now.

**Comment by PeerHerholz** [comment]
Hi @dvm-shlee,

cool, thanks a lot. I very much look forward to it!

**Comment by mwegrzyn** [comment]
Dear @dvm-shlee et al.,

my name is Martin Wegrzyn and I am one of the reviewers assigned to your submission to JOSS. Thank you for your work on BrkRaw. The following are some comments I have regarding my first impression of the package and the manuscript:

**code&examples**

- [ ]  I tried to run the notebook examples/BrkRaw_PythonAPI.ipynb but got a number of error messages and some inconsistencies with the outputs the authors uploaded on GitHub

* Cell 8: Error: “AttributeError: module 'brkraw.lib.reference' has no attribute 'METADATA_FILED_INFO'”
* Cells 15, 20 “AttributeError: 'NoneType' object has no attribute 'T'”
* Cell 37:  “TypeError: get_dataobj() got an unexpected keyword argument 'slp_correct'”
* Cell 39 (and others) different output than the one on GitHub: e.g. your affine matrix is

```python
[[  0.4    -0.      0.004 -14.381]
 [ -0.     -0.4     0.     14.968]
 [ -0.004   0.      0.4     1.824]
 [  0.      0.      0.      1.   ]]
```
mine, when running the code, is

```python
[[-0.399978	-0.000000	-0.004234	14.381493]
 [0.000000	-0.400000	-0.000000	14.968180]
 [0.004234	0.000000	-0.399978	-1.824436]
 [0.000000	0.000000	0.000000	1.000000]]
```

Hence, there are some changes in the signs (last column). Could this be a problem e.g. with left-right flips of the data?

compare: https://gist.github.com/mwegrzyn/1c8113631a4ab3fe19cf1838f3356b56


- [ ] regarding the example data, I wanted to ask whether there would be a possibility for me to confirm where left and right is in the image?
- [ ] also regarding the example data, the BOLD/EPI images seem to be 3D-files (single volume), not 4D time-series; is this correct or should I be able to see different volumes? I think it would be useful to have 4D files for testing purposes. Thank you!

- [ ] the BIDS-conversion worked very well, however, it only worked for me if I did not use the .json file and only used the .xlsx file. The command
```bash
brkraw bids_convert 20190724_114946_BRKRAW_1_1 dataset_description.xlsx -r dataset_description.json
```
did not work:
```bash
brkraw: error: unrecognized arguments: -r dataset_description.json”
```
only using
```bash
brkraw bids_convert 20190724_114946_BRKRAW_1_1 dataset_description.xlsx”
```
did work fine!

**Manuscript**

- [ ] regarding the motivation of the project, when reading the manuscript I get the feeling that you argue that nifiti-conversion is useful; also, your package has the ability to convert to nifti, which is discussed prominently in the manuscript; on the website https://brkraw.github.io/ Nifiti conversion is filed under "legacy"; hence, I am unsure why the “raw” handling of the data is so central to the tool (and its name). E.g. _“The module has been built up upon robust low-level Python Application Programming Interface (API), allowing direct raw data access without conversion to provide the advanced and easy-to-use features for data analysis.”_; here, I would like to learn more about the way you would perform analysis on raw data (without nifiti conversion). If I misunderstood, I would be happy if you could clarify. Thank you!

- [ ] you mention the work of Chris Rorden in this area. I looked at his tool Bru2Nii and was surprised to read a rather strong opinion on Bruker in the readme: _"Users should use any Bruker conversion tools with extreme caution and encourage the vendor to directly support simpler formats (e.g. creating a NIfTI "hdr" header file when the Paravision files are generated could be done seamlessly and would greatly aid customers). As a professional company, Bruker has an obligation and incentive to help users access their data. Variations of this project have existed since 1999, and yet the situation has not improved. Any customer considering purchasing equipment or services from this company should demand they develop a cleaner, more transparent solution that will reduce costs in terms of support and potentially erroneous results."_
I would be curious to learn what your opinion on this matter is and how you addressed these issues in the nifti conversion steps of your tool. 

- [ ] I think it is fair to say that the manuscript would need proofreading before being published. Also, there are some sentences where the meaning is a bit unclear. For example at the end of 1st paragraph: _“However, the preclinical MRI research using laboratory animals or objects does not require the DICOM conversion step and is rather inefficient.”_ > this sounds like preclinical MRI is inefficient, while I assume that the intended meaning is that the DICOM conversion step would be inefficient for preclinical MRI
- [ ] Figures: Overall, I found the figures difficult to understand. Maybe more extensive figure legends or in-text descriptions could be helpful (although i saw in other JOSS papers that these are usually kept to a minimum; however, I think this would be worth considering).
- [ ] Figure 1: Could you explain what we see in the _“between dataset comparison”_ and how we can visually assess successful conversion
- [ ] Figure 4: the contents of the four subplots are not readable. I would be great if you could increase the resolution of the figure. Thank you.

I hope you will find these comments helpful. Please let me know if you have any questions regarding the points I raised. Thank you for your time and consideration. 

Best,
Martin Wegrzyn
