### ISSUE TITLE
Incompatible with Python 3.8?

### ISSUE THREAD

**Issue by mih** [BrkRaw/brkraw#16]
Hey, this issue is part of my review of your JOSS submission at https://github.com/openjournals/joss-reviews/issues/2277

I am running Debian bullseye with Python 3.8.3. I cannot install brkraw using this version, because 3.8 is not a supported version.

```
      python_requires='>3.5, <3.8',
```

Going through the source code I cannot easily find a reason for that. Is 3.8 incompatible? Do you have plans to support 3.8?

**Comment by dvm-shlee** [comment]
@mih Thank you for your comments,

The supported versions are listed on the documentation page: https://brkraw.github.io/docs/gs_inst.html as 3.6 and 3.7 only
because those are only the versions I've fully tested so far.
There are few issues supporting 3.8 at this point due to some syntax changes, which I experience some unexpected bugs. 
So, I just blocked it intentionally to prevent this issue.

I would like to support 3.8 later but prefer to do it immediately, but during revising the paper and source code, I will integrate the test scripts which commented by (@PeerHerholz) to support recent versions of Python and clarify the supported python version python on the README.md.

**Comment by dvm-shlee** [comment]
Next release will support all recent python version 3.8>=
