### ISSUE TITLE
Simplifying and Reducing brkrecon submodule 

### ISSUE THREAD

**Issue by timwahoo** [BrkRaw/brkraw#160]
**Is your feature request related to a problem? Please describe.**
Brkrecon submodule code is heavily repetitive and some of the test cases are not used sometime. It would also be beneficial to start looking into reshaping the code as a plugin module.

**Describe the solution you'd like**
Simpify the recon.py and recoFunctions.py so that there is less code and more efficient in FID sorting

**Comment by dvm-shlee** [comment]
@timwahoo Hey, I apologize for not being able to prepare the working plugin, but I've pushed the latest update to the repo. I'd appreciate it if you could try integrating your code with the following structure:

```python
from brkraw.app import tonifti as tonii

rawdata_path = '20240416_xxx_xxx_1_1_1.pvdataset'
studyobj = tonii.BrkrawToNifti(rawdata_path)
scan_id = 4
scanobj = studyobj.get_scan(scan_id)

fid_buffer = scanobj.get_fid()
ni = scanobj.acqp["NI"]
method = scanobj.method["PVM_method"]
```

You can now access parameters as shown below:
- To retrieve 'NI', use `acqp.NI`, `acqp["NI"]`, or `acqp.get('NI')`. Using `acqp.get('NI')` is the safest method; it returns None instead of raising a KeyError if the parameter does not exist.

Our main goal is to ensure that the ndarray (`dataobj`) from:
```python
dataobj = studyobj.get_dataobj(scan_id, reco_id=1)
reconobj = your_recon_function(scanobj)
```
matches in shape with the one you reconstruct (`reconobj`). Here’s how you can visualize and compare them:
```python
assert dataobj.shape == reconobj.shape, "Shape mismatched"

import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 2)
ax[0].imshow(dataobj[:,:,10])
ax[1].imshow(reconobj[:,:,10])
```
If the shape and visual representation are consistent, you can convert it to a Nifti file as follows:
```python
affine = studyobj.get_affine(scan_id, reco_id)

import nibabel as nib
niiobj = nib.Nifti1Image(dataobj, affine)
niiobj.to_filename('reconfile.nii.gz')
```
This setup ensures that all orientation corrections are handled by the `get_affine` function, allowing you to focus solely on image reconstruction using a minimal set of parameters like `acqp` and binary files.

I hope this setup simplifies your coding process.

**Comment by dvm-shlee** [comment]
In addition to the functionalities previously described, you can obtain an `analyzer` instance for a specific scan using the method:
```python
analyzer = studyobj.get_scan_analyzer(scan_id, reco_id)
```
This instance enables detailed inspection of the data array, covering:
- **Data type of `fid`**: For detailed information, see `brkraw/api/helper/dataarray.py:DataArray`.
- **Frame groups**
- **Images**
- **Slicepacks**
- **Cycles**

The core logic for this functionality is implemented in:
```python
brkraw/api/analyzer/scaninfo.py:ScanInfoAnalyzer
```
Information is parsed using the corresponding helper modules, found at:
```python
brkraw/api/helper/xxx.py
```

**Important Note**: There is no need to duplicate any parameter that the `analyzer` has already processed. Considerable efforts have been made to comprehensively check the `visu` parameter.

Additional protocol information, such as `info_protocol`, is derived from `acqp` and is accessible through:
```python
brkraw/api/helper/protocol.py:Protocol
```
You can access specific protocol information using commands like:
```python
analyzer.info_protocol['sw_version']  # to retrieve the software version
analyzer.info_dataarray['fid_dtype']  # to retrieve fid datatype
```

If there are any basic parameters that you think should be included in the `info_protocol` attributes or new attributes required, please let me know. I am open to expanding the parsing routes to accommodate additional useful parameters.
