### ISSUE TITLE
Contribute low-level code to NiBabel?

### ISSUE THREAD

**Issue by mih** [BrkRaw/brkraw#20]
Hey, this issue is part of my review of your JOSS submission at openjournals/joss-reviews#2277

This package provides valuable functionality that is not available in NiBabel. However, NiBabel, arguably, is the key package for neuroimaging file format support in the Python ecosystem. It has more than 80 contributors so far, and a solid track record for keeping essential data IO procedures alive and well for a long period of time. Given that much academic software shares the lifecycle of PhD students, I consider it important to integrate as much code as possible in community-maintained projects to improve the overall resilience of the research software ecosystem.

BrkRaw's scope is clearly wider than what would be a suitable contribution for NiBabel. However, NiBabel is already a dependency, so moving low-level code into this core library would not complicate deployment for BrkRaw users.

Did you consider such a contribution?

**Comment by gdevenyi** [comment]
Does nibabel provide DICOM-to-NIFTI export? That would be equivalent to adding this code into nibabel, otherwise, I'm not sure I understand the suggestion.

**Comment by dvm-shlee** [comment]
@mih Thank you for your comment, as @gdevenyi pointed out, the low-level code aims to load Bruker raw data without conversion. The feature I added to support NiBabel NifTi object and Simple ITK image object helps the user can access the data in their convenient way without conversion. 

Since the NiBabel is not designed for the raw data conversion, I don't think the low-level code can be integrated into the NiBabel. I hope this can cover your question!
