### ISSUE TITLE
Suggestion: stack tripilot slices into single image

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/brkraw#23]
When tripilot scans are converted by https://github.com/SebastianoF/bruker2nifti the individual slice directions are stacked into a single image, rather than each 2D slice being a seperate nifti file. I think this makes more sense for conversion.

**Comment by dvm-shlee** [comment]
@gdevenyi The reason I decided to separate them is NifTi cannot store multiple orientation matrixes.
The separation will happen when the scan contains distinct orientation profiles among the slice packages.

So I think this is something I cannot integrate because it cannot assure the image orientation for each slice.
If you think still it is something needed, I may consider adding an option to merge it.

**Comment by gdevenyi** [comment]
SebastianoF/bruker2nifti at least stacks the slices in the same orientation in one file. This would reduce the file count by a small amount at least. I agree its a limitation of NIFTI, MINC handles this kind of thing fine :)

**Comment by dvm-shlee** [comment]
@gdevenyi Thank you for the information. I'm going to check if integrating MINC is feasible for this project.

For tri-pilot, probably I can make two different options whether to skip it or merge it for tonii and tonii_all option if you think this is required for the user?

**Comment by gdevenyi** [comment]
Skipping would definitely be a welcome option, I'm not aware of any uses off-console.

**Comment by dvm-shlee** [comment]
@gdevenyi hope this pull request makes some process using legacy functions convenient!
I requested your review of it. Thanks! I will close this issue since it has been a long time since opening.
