### ISSUE TITLE
output diffusion gradients

### ISSUE THREAD

**Issue by lconcha** [BrkRaw/brkraw#8]
Thanks for such an amazing tool.

Can brkraw output diffusion gradient directions and b values (bvals, bvecs)? I cannot find any information on the documentation.

**Comment by dvm-shlee** [comment]
@lconcha Hi, yes, it can generate the gradient direction, but since I don't do DTI imaging, I haven't tested much.
I just made an update that if you convert DTI scan, it will automatically generate bmat bval and bvec
It may not work for some custom sequences, because it only works when 'METHOD' parameter in 'method' file contains 'DTI' (no case sensitive ). so please let me know if it does not work for you.
Also I'm not sure the generated file is proper for the DTI image analysis. Could you make some feedback on here if you experience any issue?

The new patch made on the version 0.3.3rc8

Thank you!

**Comment by lconcha** [comment]
You are fast! Thanks for the patch.

It seems to be working properly, even for multi-shell acquisitions. 
Of note, Bruker stores gradient directions without normalizing the vectors, with those corresponding to maximum bvalue having a norm=1, and the others gradient vectors scaled according to b value. `brkraw` outputs the bvecs and bvals according to this style. Not all dMRI software likes this convention, so the user may need to normalize the gradient vectors.

I have compared the gradient directions that are obtained through `brkraw` and `mrtrix` (using `mrinfo -bvalue_scaling false -export_grad_mrtrix` (see [here](https://mrtrix.readthedocs.io/en/latest/reference/commands/mrinfo.html)) from the same data set. Note that the gradient vectors are normalized in the `mrtrix` output, and not in `brkraw` (this is not a bug, I'm just pointing it out). Also note that the _z_ gradient sign appears flipped between the two (this one I need to run more tests on different acquisiton orientations).

So, in general, your implementation seems to do the job, and I thank you for it!

![Screenshot from 2020-06-03 10-37-32](https://user-images.githubusercontent.com/5749858/83657290-4597d300-a586-11ea-9837-136043b82c9a.png)

**Comment by dvm-shlee** [comment]
@lconcha Thank you for your feedback and providing useful information. If the normalization function would be preferred, I could also integrate it so please let me know.

Regarding the Z direction, since the data from BrkRaw just extract raw value from raw data without conversion, there would be some facter that MRtrix conver it intentionally. so hope to ask if you could share raw data (at least method and visu_pars without 2dseq) of the data you present. That would be great help to figure out to resolve this issue!

Thank you!

**Comment by dvm-shlee** [comment]
@lconcha Thank you for sharing the data, but I couldn't found any clue from here what can cause the inverse-sign at the Z axis.

The only difference with my usual setting will be the animal position is Head_Prone instead of Head_Supine. but according to [this document.](https://mipav.cit.nih.gov/documentation/api/gov/nih/mipav/model/file/FileBRUKER.html)
It seems the `bvec` that I parsed from PVM_DwGradVec no need to correct the position.

And also there was some discussion on [here](https://github.com/rordenlab/dcm2niix/issues/265) regarding the invert sign issue you shown. But ended up with no answer. 

Since I'm not familiar with DTI image, could you provide later which one is the correct direction (`mrtrix` vs `brkraw`)? If you get `bvec` after Dicom conversion, it may happen at that time.

BTW, I found that there is some bug on conversion of reconstructed DTI, I will figure out the solution and patch it once I figure out.

Again, Thank you for sharing the data!

**Comment by eugenegkim** [comment]
@dvm-shlee Does bids_convert have an option to write out the bvec and bval files?

**Comment by eugenegkim** [comment]
@dvm-shlee I've found that bvec and bval files are written if the modality for the DTI scan is set to 'dwi' in the BIDS datasheet. But the modality was initially blank after running bids_helper. So maybe bids_helper can be updated to set the modality of all DTI scans to 'dwi'? And I would say that it's fine to always output the bvec and bval files.

Oh and BIDS wants the bvecs in 3 rows. They are currently written out in 3 columns.

**Comment by dvm-shlee** [comment]
@eugenegkim The BIDS helper documents are not related to the bvec and bval conversion, its internally check the parameter file. but I can make default value for DTI to have dwi.

Also, I will correct output of bvec to have 3 rows instead of 3 columns,
thank you for your suggestion and for reporting the issue!

**Comment by dvm-shlee** [comment]
@eugenegkim The bvec now has 3 rows and DTI will have default modality as dwi on BIDS excel sheet
Please let me know if you still have any issues.

**Comment by eugenegkim** [comment]
@dvm-shlee Thanks for your quick responses!

**Comment by lconcha** [comment]
Thanks for the patches. Seems to be working now. 
Regarding gradient vector sign, I cannot get dcm2niix to output gradients from bruker dicoms, so I have not been able to compare the two. I do not have much access to the scanner these days (covid), but will try to run some simple tests to figure out which version is the one that reflects the user-specified gradients.

Just a note on the new patch: the converted .nii.gz gets placed in the specified output folder, but the .bvec .bvec and .bmat files are written to the current working directory.

Thanks again for all your help.

**Comment by dvm-shlee** [comment]
@lconcha Thank you for report additional bug. I will check and make a patch for it!
