### ISSUE TITLE
Commentary/Request: Please don't commit "commented" code

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/brkraw#84]
Some recent commit changes where lines were changed are done via commenting the old code and adding new code.

This makes my diff-aligned brain very sad.

I also support doing a once-off cleanup commit to remove all these and adding it to `.git-blame-ignore-revs`

**Comment by dvm-shlee** [comment]
@gdevenyi Thank you for pointing out this. I had my code under this main branch, so intend to put all comments on the code just in case the changes are making an issue while I'm patching some changes I made recently.

Since I think it is better to commit the source code even myself through Pull requests, I will make sure to clean all comments on the next update. Thank you again!
